---
- hosts: proxmox_lxc
  become: yes
  
  tasks:        
      - name: Install Docker required packages
        ansible.builtin.package:  
          name:
            - apt-transport-https
            - ca-certificates
            - lsb-release
            - gnupg
          state: latest 
          update_cache: yes
        when: (ansible_facts['distribution'] == "Ubuntu") or
          (ansible_facts['distribution'] == "Debian")

      - name: Add signing key
        ansible.builtin.apt_key:
          url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
          state: present
        when: (ansible_facts['distribution'] == "Ubuntu") or
          (ansible_facts['distribution'] == "Debian")

      - name: Get DEB architecture
        shell: dpkg --print-architecture
        register: deb_architecture
        when: (ansible_facts['distribution'] == "Ubuntu") or
          (ansible_facts['distribution'] == "Debian")

      - name: Add repository into sources list
        ansible.builtin.apt_repository:
          repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
          state: present
          filename: docker
        when: (ansible_facts['distribution'] == "Ubuntu") or
          (ansible_facts['distribution'] == "Debian")

      - name: Install Docker
        ansible.builtin.package:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-compose-plugin
          state: latest
          update_cache: yes
        when: (ansible_facts['distribution'] == "Ubuntu") or
          (ansible_facts['distribution'] == "Debian")

      # - name: Print the gateway for each host when defined
      #   ansible.builtin.debug:
      #     msg: System {{ inventory_hostname }} is distribution {{ ansible_facts['distribution'] }}